### ISSUE TITLE
Layer slider bars behavior inconsistent

### ISSUE THREAD

**Issue by GaryHudmanAZGS** [azgs/AME-UP#12]
The slider drags have some irrational behavior.  It will select surrounding text, and send the selection circle in the wrong direction.

**Comment by NoisyFlowers** [comment]
I cannot reproduce the problem of it going in the opposite direction. But it does appear to have some odd behaviors. Text selection occurs when one drags past the slider boundaries in either dimension. It occasionally gets sticky after the initial click and continues to drag until you click again. 

These problems appear to be inherent to Angular Material, as their own demo exhibits the same behaviors (https://material.angularjs.org/latest/demo/slider). There are Issues open concerning this (https://github.com/angular/material/issues/9643, https://github.com/angular/material/issues/9362). It looks like they are wanting to change their whole way of handling gestures.

For us, we'll have to decide whether to live with it and wait for their update, avoid using md-slider, or change to a different UI framework. Since we are already iffy on the opacity interface, my guess is we'll decide to take the second option.
